using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;


using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.ApplicationServices;

namespace Atend.Base.Base
{
    public class BDesignPlan
    {

        //private int designCode;

        //public int DesignCode
        //{
        //    get { return designCode; }
        //    set { designCode = value; }
        //}
        

        //private int planCode;

        //public int PlanCode
        //{
        //    get { return planCode; }
        //    set { planCode = value; }
        //}

        //public bool Insert()
        //{
        //    SqlConnection Connection = new SqlConnection(Atend.Control.ConnectionString.cnString);
        //    SqlCommand Command = new SqlCommand("B_DesignPlan_Insert", Connection);
        //    Command.CommandType = CommandType.StoredProcedure;

        //    Command.Parameters.Add(new SqlParameter("iDesignCode", DesignCode));
        //    Command.Parameters.Add(new SqlParameter("iPlanCode", PlanCode));
        //    try
        //    {
        //        Connection.Open();
        //        Command.ExecuteNonQuery();
        //        Connection.Close();
        //        return true;
        //    }
        //    catch (System.Exception ex1)
        //    {
        //        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //        ed.WriteMessage(string.Format(" ERROR BDesignPlan.Insert {0}\n", ex1.Message));

        //        Connection.Close();
        //        return false;
        //    }

        //}


        //public bool AccessInsert()
        //{
        //    OleDbConnection Connection = new OleDbConnection("PROVIDER=Microsoft.Jet.OLEDB.4.0;Data Source=" + Atend.Control.Common.AccessPath);
            
        //    OleDbCommand Command = new OleDbCommand("B_DesignPlan_Insert", Connection);
        //    Command.CommandType = CommandType.StoredProcedure;

        //    Command.Parameters.Add(new OleDbParameter("iDesignCode", DesignCode));
        //    Command.Parameters.Add(new OleDbParameter("iPlanCode", PlanCode));
        //    try
        //    {
        //        Connection.Open();
        //        Command.ExecuteNonQuery();
        //        Connection.Close();
        //        return true;
        //    }
        //    catch (System.Exception ex1)
        //    {
        //        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //        ed.WriteMessage(string.Format(" ERROR BDesignPlan.AccessInsert {0}\n", ex1.Message));

        //        Connection.Close();
        //        return false;
        //    }

        //}

        //public static bool Delete(int DesignCode, int PlanCode)
        //{
        //    SqlConnection Connection = new SqlConnection(Atend.Control.ConnectionString.cnString);
        //    SqlCommand Command = new SqlCommand("B_DesignPlan_Delete", Connection);
        //    Command.CommandType = CommandType.StoredProcedure;
        //    Command.Parameters.Add(new SqlParameter("iDesignCode", DesignCode));
        //    Command.Parameters.Add(new SqlParameter("iPlanCode", PlanCode));
        //    try
        //    {
        //        Connection.Open();
        //        Command.ExecuteNonQuery();
        //        Connection.Close();
        //        return true;
        //    }
        //    catch (System.Exception ex1)
        //    {
        //        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //        ed.WriteMessage(string.Format(" ERROR BDesignPlan.Delete {0}\n", ex1.Message));

        //        Connection.Close();
        //        return false;
        //    }
        //}

        //public static bool AccessDelete(int DesignCode, int PlanCode)
        //{
        //    OleDbConnection Connection = new OleDbConnection("PROVIDER=Microsoft.Jet.OLEDB.4.0;Data Source=" + Atend.Control.Common.AccessPath);
            
        //    OleDbCommand Command = new OleDbCommand("B_DesignPlan_Delete", Connection);
        //    Command.CommandType = CommandType.StoredProcedure;
        //    Command.Parameters.Add(new OleDbParameter("iDesignCode", DesignCode));
        //    Command.Parameters.Add(new OleDbParameter("iPlanCode", PlanCode));
        //    try
        //    {
        //        Connection.Open();
        //        Command.ExecuteNonQuery();
        //        Connection.Close();
        //        return true;
        //    }
        //    catch (System.Exception ex1)
        //    {
        //        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //        ed.WriteMessage(string.Format(" ERROR BDesignPlan.AccessDelete {0}\n", ex1.Message));

        //        Connection.Close();
        //        return false;
        //    }
        //}

        //public static DataTable SelectAll()
        //{
        //    SqlConnection Connection = new SqlConnection(Atend.Control.ConnectionString.cnString);
        //    SqlDataAdapter adapter = new SqlDataAdapter("B_DesignPlan_Select", Connection);
        //    adapter.SelectCommand.CommandType = CommandType.StoredProcedure;

        //    DataSet dsDesignPlan = new DataSet();
        //    adapter.Fill(dsDesignPlan);
        //    return dsDesignPlan.Tables[0];
        //}

        //public static DataTable AccessSelectAll()
        //{
        //    OleDbConnection Connection = new OleDbConnection("PROVIDER=Microsoft.Jet.OLEDB.4.0;Data Source=" + Atend.Control.Common.AccessPath);
            
        //    OleDbDataAdapter adapter = new OleDbDataAdapter("B_DesignPlan_Select", Connection);
        //    adapter.SelectCommand.CommandType = CommandType.StoredProcedure;

        //    DataSet dsDesignPlan = new DataSet();
        //    adapter.Fill(dsDesignPlan);
        //    return dsDesignPlan.Tables[0];
        //}

        ////public static BDesignPlan SelectByCode(int Code)
        ////{
        ////    SqlConnection Connection = new SqlConnection(Atend.Control.ConnectionString.cnString);
        ////    SqlCommand Command = new SqlCommand("B_DesignPlan_Select", Connection);
        ////    Command.CommandType = CommandType.StoredProcedure;
        ////    Command.Parameters.Add(new SqlParameter("iCode", Code));
        ////    Connection.Open();
        ////    SqlDataReader reader = Command.ExecuteReader();
        ////    BDesignPlan designPlan = new BDesignPlan();
        ////    if (reader.Read())
        ////    {
        ////        designPlan.Code = Convert.ToInt32(reader["Code"].ToString());
        ////        designPlan.DesignCode = Convert.ToInt32(reader["DesignCode"].ToString());
        ////        designPlan.PlanCode = Convert.ToInt32(reader["PlanCode"].ToString());


        ////    }
        ////    return designPlan;
        ////}

    }
}
