using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;


using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.ApplicationServices;


namespace Atend.Base.Base
{
    public class BDesignPlanWorkOrder
    {

        //private int designCode;

        //public int DesignCode
        //{
        //    get { return designCode; }
        //    set { designCode = value; }
        //}

        //private int workOrderCode;

        //public int WorkOrderCode
        //{
        //    get { return workOrderCode; }
        //    set { workOrderCode = value; }
        //}

        //private int planCode;

        //public int PlanCode
        //{
        //    get { return planCode; }
        //    set { planCode = value; }
        //}


        //public bool Insert()
        //{
        //    SqlConnection Connection = new SqlConnection(Atend.Control.ConnectionString.cnString);
        //    SqlCommand Command = new SqlCommand("B_DesignPlanWorkOdrer_Insert", Connection);
        //    Command.CommandType = CommandType.StoredProcedure;

        //    Command.Parameters.Add(new SqlParameter("iDesignCode", DesignCode));
        //    Command.Parameters.Add(new SqlParameter("iWorkOrderCode", WorkOrderCode));
        //    Command.Parameters.Add(new SqlParameter("iPlanCode", PlanCode));
        //    try
        //    {
        //        Connection.Open();
        //        Command.ExecuteNonQuery();
        //        Connection.Close();
        //        return true;
        //    }
        //    catch (System.Exception ex1)
        //    {
        //        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //        ed.WriteMessage(string.Format(" ERROR BDesignPlanWorkOdrer.Insert {0}\n", ex1.Message));

        //        Connection.Close();
        //        return false;
        //    }

        //}

        //public bool AccessInsert()
        //{
        //    OleDbConnection Connection = new OleDbConnection("PROVIDER=Microsoft.Jet.OLEDB.4.0;Data Source=" + Atend.Control.Common.AccessPath);
            
        //    OleDbCommand Command = new OleDbCommand("B_DesignPlanWorkOdrer_Insert", Connection);
        //    Command.CommandType = CommandType.StoredProcedure;

        //    Command.Parameters.Add(new OleDbParameter("iDesignCode", DesignCode));
        //    Command.Parameters.Add(new OleDbParameter("iWorkOrderCode", WorkOrderCode));
        //    Command.Parameters.Add(new OleDbParameter("iPlanCode", PlanCode));
        //    try
        //    {
        //        Connection.Open();
        //        Command.ExecuteNonQuery();
        //        Connection.Close();
        //        return true;
        //    }
        //    catch (System.Exception ex1)
        //    {
        //        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //        ed.WriteMessage(string.Format(" ERROR BDesignPlanWorkOdrer.AccessInsert {0}\n", ex1.Message));

        //        Connection.Close();
        //        return false;
        //    }

        //}

        //public static DataTable SelectAll()
        //{
        //    SqlConnection Connection = new SqlConnection(Atend.Control.ConnectionString.cnString);
        //    SqlDataAdapter adapter = new SqlDataAdapter("B_DesignplanWorkOrder_Select", Connection);
        //    adapter.SelectCommand.CommandType = CommandType.StoredProcedure;

        //    DataSet dsDesignPlanWorkOrder = new DataSet();
        //    adapter.Fill(dsDesignPlanWorkOrder);
        //    return dsDesignPlanWorkOrder.Tables[0];
        //}


        //public static DataTable AccessSelectAll()
        //{
        //    OleDbConnection Connection = new OleDbConnection("PROVIDER=Microsoft.Jet.OLEDB.4.0;Data Source=" + Atend.Control.Common.AccessPath);
            
        //    OleDbDataAdapter adapter = new OleDbDataAdapter("B_DesignplanWorkOrder_Select", Connection);
        //    adapter.SelectCommand.CommandType = CommandType.StoredProcedure;

        //    DataSet dsDesignPlanWorkOrder = new DataSet();
        //    adapter.Fill(dsDesignPlanWorkOrder);
        //    return dsDesignPlanWorkOrder.Tables[0];
        //}

        ////public static BDesignPlanWorkOrder SelectByCode(int Code)
        ////{
        ////    SqlConnection Connection = new SqlConnection(Atend.Control.ConnectionString.cnString);
        ////    SqlCommand Command = new SqlCommand("B_DesignPlanWorkOrder_Select", Connection);
        ////    Command.CommandType = CommandType.StoredProcedure;
        ////    Command.Parameters.Add(new SqlParameter("iCode", Code));
        ////    Connection.Open();
        ////    SqlDataReader reader = Command.ExecuteReader();
        ////    BDesignPlanWorkOrder workOrder = new BDesignPlanWorkOrder();
        ////    if (reader.Read())
        ////    {
        ////        workOrder.Code = Convert.ToInt32(reader["Code"].ToString());
        ////        workOrder.DesignPlanCode = Convert.ToInt32(reader["DesignPlanCode"].ToString());
        ////        workOrder.WorkOrderCode = Convert.ToInt32(reader["WorkOrderCode"].ToString());
        ////    }
        ////    return workOrder;
        ////}



    }
}
